### ISSUE TITLE
Password requirements might be unnecessary

### ISSUE THREAD

**Issue by neongreen** [svod-music/svod#31]
* They don't prevent password reuse (an average user is likely to have a favorite “complicated” password or simply add an uppercase letter to a password used elsewhere)

* They annoy users who actually have [hard-to-guess passwords](https://xkcd.com/936/)

![image](https://cloud.githubusercontent.com/assets/1523306/15823137/0a43522c-2c02-11e6-8dfa-a60722f352b7.png)

**Comment by mrkkrp** [comment]
Resolved as part of #56. Now the only requirement is that passwords should be at least 6 characters long and it's explicitely stated in the placeholder.
