### ISSUE TITLE
The “make my email public” phrasing is hard to understand

### ISSUE THREAD

**Issue by neongreen** [svod-music/svod#32]
“Display my email address in my profile” or “Make my email public” could be better.

![image](https://cloud.githubusercontent.com/assets/1523306/15823366/03c5fd2c-2c03-11e6-9178-841cac58d083.png)

**Comment by mrkkrp** [comment]
Resolved as part of #56. Now the actual phrase is “Показывать адрес почты в моём профиле” which hopefully conveys the meaning better.
