### ISSUE TITLE
Is there any need for ordinary users to see application/confirmation dates of releases?

### ISSUE THREAD

**Issue by neongreen** [svod-music/svod#52]
It sounds like it would only be useful for admins (if at all), and if so, there's no need to clutter the pages with this information (“заявка подана”, “заявка удовлетворена”).

![image](https://cloud.githubusercontent.com/assets/1523306/15896681/fcc516fa-2d99-11e6-96da-fa8889340981.png)

**Comment by neongreen** [comment]
Just in case, authors themselves should probably be able to see that info anyway.

**Comment by mrkkrp** [comment]
That's how it works. Only released albums are visible to ordinary users. Pending albums are only visible to their authors and admins/staff.
