### ISSUE TITLE
Song pages should have more explicit links to the author/album

### ISSUE THREAD

**Issue by neongreen** [svod-music/svod#53]
(because it makes sense to share those pages to other people who want to listen to the song).

![image](https://cloud.githubusercontent.com/assets/1523306/15896770/5a6ac16a-2d9a-11e6-8298-12859580a907.png)

**Comment by neongreen** [comment]
Update: I just realised that there *are* links, but they don't really get perceived as links and I believe that someone who isn't a user of Svod wouldn't be able to find them easily.

**Comment by mrkkrp** [comment]
Resolved as part of #58.
